version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=clinical_assistant
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./data:/app/data

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=clinical_assistant

volumes:
  mongo_data: