apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-insight-assistant
  labels:
    app: clinical-insight-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinical-insight-assistant
  template:
    metadata:
      labels:
        app: clinical-insight-assistant
    spec:
      containers:
      - name: clinical-insight-assistant
        image: clinical-insight-assistant:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: DB_NAME
          value: "clinical_assistant"
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongo-url
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: gemini-api-key
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: clinical-insight-assistant-service
spec:
  selector:
    app: clinical-insight-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  mongo-url: <base64-encoded-mongo-url>
  gemini-api-key: <base64-encoded-gemini-api-key>